language: rust

addons:
  apt:
    packages:
      - binutils-dev
      - build-essential
      - cmake
      - g++
      - gcc
      - libcurl4-openssl-dev
      - libdw-dev
      - libelf-dev
      - libiberty-dev
      - zlib1g-dev
rust:
  - stable

dist: trusty
sudo: required

cache:
  directories:
    - $HOME/.cargo
    - $HOME/.local
    - $TRAVIS_BUILD_DIR/target

jobs:
  include:
    # Build and tests without pre-compiled libsodium library on Linux OS.
    - name: linux
      os: linux
      script:
        - cargo test
    # Build and tests with pre-compiled `libsodium` library on Linux OS.
    - name: linux precompile
      os: linux
      install:
        - sudo add-apt-repository -y ppa:elt/libsodium
        - sudo apt-get -qq update
        - sudo apt-get -qq --yes install pkg-config libsodium-dev
      script:
        - cargo test
    # Build and tests without pre-compiled libsodium library on MacOS.
    - name: macos
      os: osx
      script:
        - cargo test
    # Build and tests without pre-compiled libsodium library on Windows OS.
    - name: windows
      os: windows
      script:
        - cargo test --tests
    # Run clippy linter with pre-compiled libsodium library on Linux OS.
    - name: clippy
      os: linux
      install:
        - sudo add-apt-repository -y ppa:elt/libsodium
        - sudo apt-get -qq update
        - sudo apt-get -qq --yes install pkg-config libsodium-dev
        - rustup component add clippy-preview
      script:
        - cargo clippy --all -- -D warnings
